### PR TITLE
Add admin workflow rebuild command

### PR DESCRIPTION
**Pull request by wxing1292**
## What was changed

* Add admin workflow rebuild command

## Why?

See above

## Checklist

1. Closes 

2. How was this tested:

This PR only creates the admin command, business logic is tested [here](https://github.com/temporalio/temporal/blob/master/host/admin_test.go)

3. Any docs updates needed?

### CODE REVIEW

**Comment by feedmeapples** [comment]
@wxing1292 since admin commands are now moved to their own Temporal tool https://github.com/temporalio/temporal/tree/master/cmd/tools/tdbg (primarily meant for Temporal devs and not as much for external users), could you open a PR there

**Comment by feedmeapples** [comment]
plus this repo is going to make switch to the new UX soon (`cli` folder instead of `cli_curr`), possibly with Temporal release v1.18

**Comment by wxing1292** [comment]
> @wxing1292 since admin commands are now moved to their own Temporal tool https://github.com/temporalio/temporal/tree/master/cmd/tools/tdbg (primarily meant for Temporal devs and not as much for external users), could you open a PR there

sure

**Comment by wxing1292** [comment]
closed in favor of https://github.com/temporalio/temporal/pull/3175

**Pull request closed without merging**
